# This file defines the backend application.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        # The ECR URL for your backend image.
        image: 267092042432.dkr.ecr.us-west-2.amazonaws.com/todo-backend:latest
        ports:
        - containerPort: 5000 # The port your Flask app listens on
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb-service:27017/todo-db" # Connects to the new internal MongoDB service
---
# This service provides a stable internal network address for the backend.
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
